"""Eliminé los campos advisor y user, ya que basta con tener los id de ambos como llaves foráneas

Revision ID: 790c8e9e29af
Revises: c5ac79ec2685
Create Date: 2024-06-19 14:48:29.890783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '790c8e9e29af'
down_revision: Union[str, None] = 'c5ac79ec2685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
